name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
        profile: [test, release]

    steps:
    - uses: actions/checkout@v4
    - name: Select toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose --profile ${{ matrix.profile }}
    - name: Run tests
      run: cargo test --verbose --profile ${{ matrix.profile }}
